name: Test Dotfiles

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Test Environment
      run: |
        mkdir -p ${{ runner.temp }}/test-home
        mkdir -p ${{ runner.temp }}/test-dotfiles
        echo "HOME=${{ runner.temp }}/test-home" >> $GITHUB_ENV
        echo "DOTFILES_TEST_MODE=1" >> $GITHUB_ENV
        echo "RUNNER_TEMP=${{ runner.temp }}" >> $GITHUB_ENV

    - name: Setup macOS Dependencies
      if: matrix.os == 'macos-latest'
      run: |
        # Install Homebrew if not present (should be installed on runners)
        if ! command -v brew &> /dev/null; then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi

    - name: Setup Bats and bats libs
      id: setup-bats
      uses: bats-core/bats-action@3.0.0

    - name: Setup Windows Dependencies
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        # Install Pester for testing
        Install-Module -Name Pester -Force -SkipPublisherCheck -MinimumVersion 5.0
        Import-Module Pester
        
        # Set test environment variables
        $env:NO_SYSTEM_CHANGES = "1"
        $env:SKIP_ADMIN_TESTS = "1"
        
        # Create test registry hive
        $env:TEST_REGISTRY_PATH = "HKCU:\Software\DotfilesTest"
        New-Item -Path $env:TEST_REGISTRY_PATH -Force

    - name: Install WinGet
      if: matrix.os == 'windows-latest'
      uses: Cyberboss/install-winget@v1

    - name: macOS Tests
      if: matrix.os == 'macos-latest'
      uses: bats-core/bats-action@1.5.4
      with:
        tests: ./tests/*.bats
        continue-on-error: true

    - name: Windows Setup
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        $config = New-PesterConfiguration
        $config.Run.Path = "./tests"
        $config.Output.Verbosity = "Detailed"
        $config.Filter.Tag = "Setup"
        $config.Run.SkipRemainingOnFailure = 'None'
        Invoke-Pester -Configuration $config

    - name: Windows Uninstall
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        $config = New-PesterConfiguration
        $config.Run.Path = "./tests"
        $config.Output.Verbosity = "Detailed"
        $config.Filter.Tag = "Uninstall"
        Invoke-Pester -Configuration $config
